### PR TITLE
Fix for boolean return values encoded as `c`

### PR DESCRIPTION
**Pull request by mojo2012**
`boolean` return values are now correctly handled when using a signature like `c@:`
Also some more KVO selectors are implemented and redirected to the java peer

### CODE REVIEW

**Comment by mojo2012** [comment]
Basically this PR contain:
* proper handling of nsstring subclasses
* some (probably not all) KVO related selectors forwarded to java (KV from java objects to java objects works too)
* java11 automatic module config
* switched to maven build system (netbeans/ant build didn't work for me at all)
* boolean values ('c' symbol definition) didn't work correctly
* redirect all unimplemented proxy methods to java
* restructured code base to match maven style

If you have time you can look at the changes an manually copy what you need.
I will probably merge the project (including my changes) into https://github.com/mojo2012/kakao.
As kakao is a maven project I need j-o-c-bridge to be a maven artifact too (hence the change)

**Comment by shannah** [comment]
Kakao looks interesting.  I like the direction of this pull request but there are some details that need to be finished.  E.g.

1. The README file needs to be updated with new build and usage instructions.
2. When building with `mvn package`, the tests fail.  This is likely because the dylib isn't built directly.  
3. The repo no longer includes the prebuilt dylib.  It would be really nice if we could have the maven build run xcodebuild on the dylib project to automatically build and include the dylib.

**Comment by mojo2012** [comment]
Yes you are absolutely right. I was planning to do this but kinda forgot about it.
I will update the readme and use maven to build the dylib.

**Comment by shannah** [comment]
I just checked out your latest.  It seems that `mvn clean install` will build the library with Xcode build.  But tests still fail.  It doesn't seem to copy the dylib anywhere.  Am I missing something in the build process?

**Comment by mojo2012** [comment]
Sorry for that (it worked on my machine ...). I fixed the build and now the tests should work for you too.

**Comment by shannah** [comment]
Great!  Thanks!

**Pull request merged**
